---
# tasks file for roles/lasair_service

- name: Install packages
  become: yes
  apt:
      name: 
        - swig
        - python3-dev
        - python3-pip
      state: present
      update_cache: true

- name: Install python packages
  pip:
      executable: pip3
      name:
        - gkhtm
        - gkutils
        - docopt
        - numpy
        - mocpy
        - requests
        - mysql-connector-python

- name: Make sure the repo is up to date
  git: 
      repo: https://github.com/lsst-uk/lasair4.git
      dest: "{{ ansible_env.HOME }}/lasair4"

- import_tasks: cron.yml
- import_tasks: settings.yml
