---
- hosts: all
  gather_facts: true

- hosts: all:!localhost
  gather_facts: false
  roles:
    - lasair_instance

- hosts: kafka
  gather_facts: false
  vars_files:
    - settings.yaml
  vars:
    internal_only: true
    source: localhost:9092 # fake source for testing
  roles:
    - kafka
    - mirrormaker # we currently run mirrormaker on the same hosts as kafka 
  tags: kafka

- hosts: kafka_pub
  gather_facts: false
  vars_files:
    - settings.yaml
  vars:
    internal_only: false
    dns_lookup: false # disable dns checks for testing
    kafka_secret: "{{ lookup('hashi_vault', 'secret='+vault.path+'/kafka url='+vault.url)}}"
  roles:
    - kafka
  tags: kafka_pub


