---
- hosts: all
  gather_facts: true
  tags: facts

- hosts: all:!localhost
  gather_facts: false
  vars_files:
    - settings.yaml
  roles:
    - lasair_instance
  tags:
    - lasair_instance

- hosts: svc
  gather_facts: false
  vars_files:
    - settings.yaml
    - exports.yaml
  vars:
    enable_letsencrypt: false
  roles:
    - lasair_cephfs
    - lasair_service
    - prometheus
    - grafana
  tags: svc

- hosts: kafka
  gather_facts: false
  vars_files:
    - settings.yaml
  vars:
    internal_only: true
    source: localhost:9092 # fake source for testing
  roles:
    - kafka
    - mirrormaker # we currently run mirrormaker on the same hosts as kafka 
  tags: kafka

- hosts: kafka_pub
  gather_facts: false
  vars_files:
    - settings.yaml
  vars:
    internal_only: false
    dns_lookup: false # disable dns checks for testing
  roles:
    - kafka
  tags: kafka_pub

- hosts: ingest
  gather_facts: false
  vars_files:
    - settings.yaml
    - exports.yaml
  roles:
    - lasair_cephfs
    - ingest
  tags: ingest
  
- hosts: sherlock
  gather_facts: false
  vars_files:
    - settings.yaml
    - exports.yaml
  vars:
    settings: "{{ lookup('hashi_vault', 'secret='+vault.path+'/settings url='+vault.url)}}"
    mysql_root_password: "{{ settings.local_db_root_password }}"
    datadir: /var/lib/mysql
    is_sherlock: true
  roles:
    - lasair_cephfs
    - gkansible.gkservercollection.mariadb
    - sherlock
  tags: sherlock
  
- hosts: filter
  gather_facts: false
  vars_files:
    - settings.yaml
  vars:
    db_host: "{{ (groups['db'] + groups['cluster_control'])[0] }}"
    db_port: "{% if groups['db'] %}3306{% else %}9001{% endif %}"
  roles:
    - filter
  tags: filter

- hosts: web
  gather_facts: false
  vars_files:
    - settings.yaml
    - exports.yaml
  vars:
    db_host: "{{ (groups['db'] + groups['cluster_control'])[0] }}"
    db_port: "{% if groups['db'] %}3306{% else %}9001{% endif %}"
    sherlock_svc_host: "{{ groups['sherlock'][0] }}"
    cassandra_head: "{{ groups['cassandranodes']"
  roles:
    - lasair_cephfs
    - webserver
  tags: web
