---
- hosts: localhost
  vars_files: 
    - settings.yaml
 
  tasks:
          
  - name: Check Ansible version
    assert:
      that: ansible_version.full >= "2.10.0" 
      fail_msg: "Ansible version >= 2.10 required"
      quiet: true

  - name: Check vault token
    assert:
      that: ansible_env.VAULT_TOKEN is defined
      fail_msg: "VAULT_TOKEN is not set"
      quiet: true

  - name: Create token file
    ansible.builtin.copy:
      content: "{{ ansible_env.VAULT_TOKEN }}"
      mode: 0600
      dest: "{{ ansible_env.HOME }}/.vault-token"

  - name: Create bash profile if necessary
    ansible.builtin.copy:
      content: "if [ -f ~/.bashrc ]; then . ~/.bashrc; fi"
      dest: "{{ ansible_env.HOME }}/.bash_profile"
      force: false

  - name: Set vault env vars in profile
    ansible.builtin.lineinfile:
      create: yes
      path: "{{ ansible_env.HOME }}/.bash_profile"
      line: "{{ item }}"
    with_items:
      - "export VAULT_TOKEN=`cat ~/.vault-token`"
      - "export VAULT_ADDR='{{ vault.url }}'"

  - name: Add vault public key
    vars:
      settings: "{{ lookup('hashi_vault', 'secret='+vault.path+'/settings url='+vault.url, token_validate='false')}}"
    ansible.builtin.lineinfile:
      create: yes
      path: "{{ ansible_env.HOME }}/.ssh/authorized_keys"
      line: "{{ settings.id_rsa_pub }}"
      mode: 0600

  - name: Install apt packages
    become: true
    apt:
      pkg: 
        - python3-hvac
        - kafkacat
        - python3-openstackclient
        - python3-heatclient
        - python3-manilaclient
        - python3-mysql.connector
      state: present
      update-cache: yes

  - name: Install vault snap
    become: true
    community.general.snap:
      name:
        - vault

  - name: Set SSH client config
    copy:
      dest: ~/.ssh/config
      mode: 0600
      content: |
        Host *
          StrictHostKeyChecking accept-new

  - name: Install collections
    command: ansible-galaxy collection install -r requirements.yaml -p collections/

#  - name: Install roles
#    command: ansible-galaxy role install -r requirements.yaml -p roles/

  - name: update inventory
    ini_file:
      path: "{{ lookup('env', 'PWD') }}/hosts"
      section: login
      allow_no_value: true
      option: "localhost ansible_connection=local"
        

