---
- hosts: localhost
  vars_files: 
    - settings.yaml
 
  tasks:
          
  - name: Install apt packages
    become: true
    apt:
      pkg: 
        - python3-hvac
        - kafkacat
      state: present
      update-cache: yes

  - name: Set SSH client config
    copy:
      dest: ~/.ssh/config
      mode: 0600
      content: |
        Host *
          StrictHostKeyChecking accept-new

  - name: Install collections
    command: ansible-galaxy collection install -r requirements.yaml -p collections/

#  - name: Install roles
#    command: ansible-galaxy role install -r requirements.yaml -p roles/

  - name: update inventory
    ini_file:
      path: "{{ lookup('env', 'PWD') }}/hosts"
      section: login
      allow_no_value: true
      option: "localhost ansible_connection=local"
        

