---
- hosts: localhost
  vars_files: 
    - settings.yaml
 
  tasks:
          
  - name: Set SSH client config
    copy:
      dest: ~/.ssh/config
      mode: 0600
      content: |
        Host *
          StrictHostKeyChecking accept-new

  - name: Install collections
    command: ansible-galaxy collection install -r requirements.yaml -p collections/

#  - name: Install roles
#    command: ansible-galaxy role install -r requirements.yaml -p roles/

