---
#roles:
  #- src: git+https://github.com/gpfrancis/test-role.git
  #- src: git+https://github.com/genghisken/gkansible.git#/gkansible/roles/install-mysql-sherlock

collections:
  - openstack.cloud
  - community.general
  - name: git+https://github.com/genghisken/gkansible.git
    type: git
    version: master

