---

# DNS domain where this deployment lives
domain: lasair-test.lsst.ac.uk
# A name to distinguish *this* lasair deployment, typically the same as the first part of the domain
lasair_name: lasair-test

# Instances to deploy
instances:
  svc:
  web:
  db:
  kafka:
    number: 0
  kafka_pub:
  ingest:
    number: 0
  sherlock:
    number: 0
  filter:
    number: 0
  cassandra:
    number: 0

# Vault settings
vault:
  url: https://vault.lsst.ac.uk
  path: secret/lasair

# OpenStack configuration
os:
  # Name of the base image
  image_name: ubuntu-focal
  # Name of the private network
  network_name: test
  # Name of the network to use for Manila shares
  share_network_name: cephfs
  # Size of shared filesystem in GB
  share_size: 10
  # Ceph username for shared filesystem
  share_user: gareth-test
  # Name of the ssh keypair in OpenStack
  keypair_name: gareth-somerville
  # What to call the heat stack
  # Use different names for multiple deployments in the same project
  stack_name: "{{ lasair_name }}"
  # names of flavors to use
  flavor_small: m1.tiny
  flavor_medium: m1.small
  flavor_large: m1.medium
  flavor_xlarge: m1.large

