---

# Configuration for Lasair deployment

# OpenStack configuration
os:

  # Name of the private network
  network_name: LSST - Private Network

  # Name of the ssh keypair in OpenStack
  keypair_name: lasair-key

  # What to call the heat stack
  # Use different names for multiple deployments in the same project
  stack_name: lasair-dev

# Instances to deploy
instances:
  svc:
  kafka:
    number: 4
  ingest:
    number: 4
  sherlock:
    number: 4
  filter:
    number: 4
  cassandra:
    number: 5
