---

# Configuration for Lasair deployment

# OpenStack configuration
os:

  # Name of the private network
  network_name: LSST - Private Network

  # Name of the ssh keypair in OpenStack
  keypair_name: lasair-key

  # What to call the heat stack
  # Use different names for multiple deployments in the same project
  stack_name: lasair-dev

  # names of flavors to use
  flavor_small: c3.small
  flavor_medium: c3.medium
  flavor_large: c3.large
  flavor_xlarge: c3.xlarge

# Instances to deploy
instances:
  svc:
  web:
  kafka:
    number: 1
  ingest:
    number: 0
  sherlock:
    number: 0
  filter:
    number: 0
  cassandra:
    number: 0
