---

# DNS domain where this deployment lives
domain: lsst.ac.uk
# A name to distinguish *this* lasair deployment, typically the same as the first part of the domain
lasair_name: lasair-test

# Instances to deploy
instances:
  db:
    create: true
    volume_size: 5
  frontend_db:
    number: 0
    volume_size: 5
  backend_db:
    number: 0
    volume_size: 5
  cluster_control:
    create: false
  svc:
    create: true
  web:
    create: true
  kafka:
    number: 1
  kafka_pub:
    create: true
    volume_size: 15
  ingest:
    number: 1
  sherlock:
    number: 1
    volume_size: 5
  filter:
    number: 1
  cassandranodes:
    number: 0
    volume_size: 5

# Size of shared filesystem in GB
share_size: 10

# tpye of Sherlock install - set to one of empty/lite/test/full
sherlock_import_type: empty

# Vault settings
vault:
  url: https://vault.lsst.ac.uk
  path: secret/lasair

# An admin email address for services that expect one
admin_email: lasair-help@lists.roe.ac.uk

# CephFS export location for the Sherlock database share
sherlock_share: "10.19.4.16:6789,10.19.4.17:6789,10.19.4.18:6789:/volumes/_nogroup/f7d66a57-bdce-4924-8817-4b968ca9648f/7a8807b0-f30d-46a5-820a-1114071e5a04"

# OpenStack configuration
os:
  # Name of the base image
  image_name: ubuntu-focal
  # Name of the private network
  network_name: lasair-test
  # Name of the network to use for Manila shares
  share_network_name: cephfs
  # Ceph username for shared filesystem
  # Should be unique to this deployment
  share_user: "{{ lasair_name }}"
  # Volume type to use for "fast" volumes
  fast_volume_type: ceph-ssd
  # Volume type to use for "slow" volumes
  slow_volume_type: ceph-hdd
  # Name of the ssh keypair in OpenStack
  keypair_name: lasair-test
  # What to call the heat stack
  # Use different names for multiple deployments in the same project
  stack_name: "{{ lasair_name }}"
  # names of flavors to use
  flavor_small: tiny
  flavor_medium: small
  flavor_large: medium
  flavor_xlarge: large
  flavor_kafka: kafka-test
  flavor_database: database-large

