---

# DNS domain where this deployment lives
domain: lasair-test2.lsst.ac.uk
# A name to distinguish *this* lasair deployment, typically the same as the first part of the domain
lasair_name: lasair-test2

# Instances to deploy
instances:
  db:
    create: false
    volume_size: 5
  frontend_db:
    number: 1
    volume_size: 5
  backend_db:
    number: 2
    volume_size: 5
  cluster_control:
    create: true
  svc:
    create: true
  web:
    create: true
  kafka:
    number: 1
  kafka_pub:
    create: true
    volume_size: 15
  ingest:
    number: 1
  sherlock:
    number: 2
  filter:
    number: 1
  cassandra:
    number: 1
    volume_size: 15

# Size of shared filesystem in GB
share_size: 10

# Vault settings
vault:
  url: https://vault.lsst.ac.uk
  path: secret/lasair

# An admin email address for services that expect one
admin_email: admin@example.com

# OpenStack configuration
os:
  # Name of the base image
  image_name: ubuntu-focal
  # Name of the private network
  network_name: test
  # Name of the network to use for Manila shares
  share_network_name: cephfs
  # Ceph username for shared filesystem
  # Should be unique to this deployment
  share_user: "{{ lasair_name }}"
  # Volume type to use for "fast" volumes
  fast_volume_type: ceph-ssd
  # Volume type to use for "slow" volumes
  slow_volume_type: ceph-hdd
  # Name of the ssh keypair in OpenStack
  keypair_name: gareth-somerville
  # What to call the heat stack
  # Use different names for multiple deployments in the same project
  stack_name: "{{ lasair_name }}"
  # names of flavors to use
  flavor_small: tiny
  flavor_medium: small
  flavor_large: medium
  flavor_xlarge: large
  flavor_kafka: kafka-test

