---

- name: deploy stack

  hosts: localhost
  gather_facts: False

  vars_files:
    - settings.yaml

  vars:
    template: heat_template.yaml

  tasks:

    - name: create stack
      register: stack_create
      openstack.cloud.stack:
        name: "{{ os.stack_name }}"
        state: present
        template: "{{ template }}"
        parameters:
          key_name: "{{ os.keypair_name }}"

    - name: update /etc/hosts
      become: true
      lineinfile:
        path: /etc/hosts
        regexp: '\s{{ os.stack_name }}-{{ item.output_key }}$'
        line: "{{ item.output_value }} {{ os.stack_name }}-{{ item.output_key }}"
      loop: "{{ stack_create.stack.outputs }}"
      when: item.description == "Private IP"

    - name: update inventory
      ini_file:
        path: hosts
        section: "{{ item.role }}"
        allow_no_value: true
        option: "{{ os.stack_name }}-{{ item.role }}{{ item.suffix }}"
      loop: |
        [
        {%- for role,values in instances.items() %}
          {%- if values.number is defined %}
            {%- for i in range(1, values.number+1) %}
              { 'role': '{{ role }}', 'suffix': '-{{ i }}' },
            {%- endfor %}
          {%- else %}
            { 'role': '{{ role }}', 'suffix': '' },
          {%- endif %}
        {%- endfor %}
        ]
      loop_control:
        label: "{{ os.stack_name }}-{{ item.role }}{{ item.suffix }}"
