---
- name: Install Ceph packages
  become: true
  apt:
      name:
        - ceph-common
      state: present
      update_cache: true

- name: Create /etc/ceph directory
  become: true
  file:
    path: /etc/ceph
    state: directory
    mode: '0755'

- name: Create sherlock secret file
  become: true
  template:
    src: ceph.sherlock.secret.j2
    dest: /etc/ceph/ceph.sherlock.secret
    mode: '0600'

- name: Create sherlock mountpoint
  become: true
  file:
    path: /mnt/sherlock
    state: directory
    mode: '0777'

- name: Configure and mount sherlock CephFS
  become: true
  mount:
    boot: false
    fstype: ceph
    opts: "secretfile=/etc/ceph/ceph.sherlock.secret,name=sherlock"
    path: /mnt/sherlock
    src: "{{ sherlock_share }}"
    state: mounted

