---
- name: Install Ceph packages
  become: true
  apt:
      name:
        - ceph-common
      state: present
      update_cache: true

- name: Create /etc/ceph directory
  become: true
  file:
    path: /etc/ceph
    state: directory
    mode: '0755'

- name: Create secret file
  become: true
  template:
    src: ceph.secret.j2
    dest: /etc/ceph/ceph.secret
    mode: '0600'

- name: Create mountpoint
  become: true
  file:
    path: /mnt/cephfs
    state: directory
    mode: '0755'

- name: Configure and mount CephFS
  become: true
  mount:
    boot: false
    fstype: ceph
    opts: "secretfile=/etc/ceph/ceph.secret,name={{ os.share_user }}"
    path: /mnt/cephfs
    src: "{{ ceph.exports }}"
    state: mounted

- name: Create lasair directories
  become: true
  file:
    path: "/mnt/cephfs/{{ item }}"
    state: directory
    owner: "{{ ansible_env.USER }}"
    mode: '0755'
  with_items:
    - lasair
    - lasair/areas
    - lasair/fits
    - lasair/services_log
    - lasair/streams
    - lasair/system_status
    - lasair/watchlists

