---

- name: "Create data filesystems"
  become: true
  filesystem:
    fstype: "{{ data_fs.type }}"
    dev: "{{ data_fs.dev }}"

- name: "Create data mountpoints"
  become: true
  file:
    path: "{{ data_fs.path }}"
    state: directory

- name: "Mount data filesystems"
  become: true
  mount:
    path: "{{ data_fs.path }}"
    src: "{{ data_fs.dev }}"
    fstype: "{{ data_fs.type }}"
    opts: nofail
    state: mounted

- name: "Create data directory"
  become: true
  file:
    path: "{{ data_fs.path }}/data"
    state: directory
    mode: 0777

- name: "Deploy Kafka compose file"
  template:
    src:  kafka-compose.yaml.j2
    dest: kafka-compose.yml
  vars:
    mntpath: "{{ data_fs.path }}/data"
    logpath: "{{ data_fs.path }}/data"

- name: "Start Kafka services"
  become: true
  docker_compose:
    project_src:
        '.'
    files:
      - kafka-compose.yml
    services:
      - kafka
    state:
      present
