---

- name: "Install packages"
  become: true
  apt:
    pkg:
      - python3-pip
      - swig
      - zlib1g
    state: present
    update-cache: true

- name: "Install python packages"
  become: true
  pip:
    name:
      - confluent-kafka
      - fastavro
      - gkhtm
      - cassandra-driver
      - gkutils
      - gkdbutils
      - docopt

- name: Make sure the repo is up to date
  git: 
    repo: https://github.com/lsst-uk/lasair4.git
    dest: "{{ ansible_env.HOME }}/lasair4"

- name: Create logs directory
  file:
    path: "{{ ansible_env.HOME }}/logs"
    state: directory

