---

- name: "Create /opt/lasair directory"
  become: true
  file:
    path: /opt/lasair
    state: directory
    owner: "{{ ansible_user_id }}"

- name: "Deploy service config"
  template:
    src:  service_settings.yaml.j2
    dest: /opt/lasair/sherlock_service_settings.yaml

- name: "Install apt packages"
  become: true
  apt:
    name:
      - gcc
      - g++
      - python3
      - python3-dev
      - python3-yaml
      - python3-pip
      - nginx

- name: "Install pip packages"
  pip:
    name:
      - flask-restful
      - uwsgi
      - numpy

- name: "Install pip packages"
  pip:
    name:
      - qub-sherlock==2.3.0

- name: "Copy main.py"
  get_url:
    url: "https://raw.githubusercontent.com/lsst-uk/lasair4/{{ lasair_version }}/services/sherlock/main.py"
    dest: /opt/lasair/main.py
    mode: 0644

- name: "Create uwsgi ini file"
  template:
    src:  sherlock_service.ini.j2
    dest: /opt/lasair/sherlock_service.ini

- name: Create systemd service file
  become: true
  copy:
    src: sherlocksvc.service
    dest: /etc/systemd/system/sherlocksvc.service

- name: Make sure service unit is running
  become: true
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: sherlocksvc

- name: Create nginx site file
  become: true
  copy:
    src: sherlocksvc.nginx
    dest: /etc/nginx/sites-available/sherlocksvc

- name: Link nginx site file
  become: true
  file:
    src: /etc/nginx/sites-available/sherlocksvc
    dest:  /etc/nginx/sites-enabled/sherlocksvc
    state: link

- name: Unlink default nginx site file
  become: true
  file:
    path:  /etc/nginx/sites-enabled/default
    state: absent

# could make this a handler
- name: Restart sherlocksvc
  become: true
  ansible.builtin.systemd:
    name: sherlocksvc.service
    state: restarted

# could make this a handler
- name: Restart nginx
  become: true
  ansible.builtin.systemd:
    name: nginx.service
    state: restarted

