---

- name: Create Sherlock user
  community.mysql.mysql_query:
    query:
      - CREATE USER IF NOT EXISTS '{{ sherlock_user }}'@'%' IDENTIFIED BY '{{ sherlock_password }}'
      - GRANT SELECT, SHOW VIEW ON crossmatch_catalogues.* TO '{{ sherlock_user }}'@'%'
    login_host: 127.0.0.1
    login_user: root
    login_password: "{{ mysql_root_password }}"
    single_transaction: yes

- name: Load schema
  ansible.builtin.shell: mysql -u root --password={{ mysql_root_password | quote }} {{ db_name | quote }} < /mnt/sherlock/sherlock_schema.sql

