---

- name: Install apt packages
  become: true
  apt: 
    name: 
      - python3-pip
      - apache2
      - apache2-dev
      - apache2-utils
      - libexpat1
      - ssl-cert
      - libmysqlclient-dev
      - swig
      - postfix
    state: present
    update_cache: true

- name: Install python packages
  pip: 
    executable: pip3 
    name: 
      - mysql-connector-python
      - mysqlclient
      - django
      - djangorestframework
      - pyephem
      - requests
      - MOCpy
      - astropy
      - cassandra-driver
      - gkhtm
      - gkutils
      - gkdbutils
      - mod_wsgi-httpd
      - mod_wsgi
      - confluent-kafka
      - fastavro

- name: Create WSGI directory
  file:
      path: "{{ ansible_env.HOME }}/mod_wsgi_space"
      state: directory

- name: Make sure the repo is up to date
  git:
      repo: https://github.com/lsst-uk/lasair4.git
      dest: "{{ ansible_env.HOME }}/lasair4"
      
# lasair4/common/settings.py
- import_tasks: settings.yml

- name: Settings.py for django
  template:
    src:  settings.py.j2
    dest: "{{ ansible_env.HOME }}/lasair4/webserver/lasair/settings.py"

- name: Create restart script
  template:
    src: restart_webserver.sh.j2
    dest: restart_webserver.sh
    mode: 0755

- name: Restart web server
  command:
    cmd: "{{ ansible_env.HOME }}/restart_webserver.sh"

- name: Enable Apache modules
  become: true
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items:
    - rewrite
    - proxy
    - proxy_http
    - proxy_balancer
    - lbmethod_byrequests
  notify:
    - restart_apache2

- name: Set Apache site config
  become: true
  template:
    src: 000-default.conf
    dest: /etc/apache2/sites-available/000-default.conf
  notify:
    - reload_apache2

- name: Django bootstrap
  shell:
    chdir: "{{ ansible_env.HOME }}/lasair4/webserver"
    cmd: "python3 manage.py {{ item }}"
  environment:
    PYTHONPATH: "{{ ansible_env.HOME }}/lasair4/webserver/lasair"
  with_items:
    - migrate
    - makemigrations lasair
    - migrate
    - collectstatic --noinput

- name: Create symlink for services log
  file:
    src: /mnt/cephfs/lasair/services_log
    dest: "{{ ansible_env.HOME }}/lasair4/webserver/static/services_log"
    state: link

- name: Create symlink for streams
  file:
    src: /mnt/cephfs/lasair/streams
    dest: "{{ ansible_env.HOME }}/lasair4/webserver/static/streams"
    state: link

- name: Create Django superuser
  shell:
    chdir: "{{ ansible_env.HOME }}/lasair4/webserver"
    cmd: "python3 manage.py createsuperuser --noinput --username su --email {{ admin_email }}"
  environment:
    PYTHONPATH: "{{ ansible_env.HOME }}/lasair4/webserver/lasair"
    DJANGO_SUPERUSER_PASSWORD: "{{ django_password }}"
  ignore_errors: true

