
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    # Override the global default and scrape targets from this job every 5 seconds.
    #scrape_interval: 5s
    #scrape_timeout: 5s
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ['localhost:9090']

  - job_name: websites
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
     - targets:
       - "https://www.{{ domain }}/"
       - "https://{{ (groups['web'] + ['localhost'])[0] }}/"
    relabel_configs:
     - source_labels: [__address__]
       target_label: __param_target
     - source_labels: [__param_target]
       target_label: instance
     - target_label: __address__
       replacement: 127.0.0.1:9115 # The blackbox exporter.

  - job_name: public-kafka
    metrics_path: /probe
    params:
      module: [tcp_connect]
    static_configs:
     - targets:
       - "kafka.{{ domain }}:9092"
       - "{{ (groups['kafka_pub'] + ['localhost'])[0] }}:9092"
    relabel_configs:
     - source_labels: [__address__]
       target_label: __param_target
     - source_labels: [__param_target]
       target_label: instance
     - target_label: __address__
       replacement: 127.0.0.1:9115 # The blackbox exporter.

  - job_name: svc-node
    # If prometheus-node-exporter is installed, grab stats about the local
    # machine by default.
    static_configs:
      #- targets: ['localhost:9100']
      - targets:
        {% for host in (groups['all']) -%}
        - "{{ host }}:9100"
        {% endfor %}

  - job_name: kafka-nodes
    static_configs:
      - targets: 
        {% for host in (groups['kafka'] + groups['kafka_pub']) -%}
        #- "{{ host }}:9100"
        - "{{ host }}:8081"
        - "{{ host }}:8082"
        - "{{ host }}:8083"
        {% endfor %}

    metric_relabel_configs:
      # Relabel: topic=ztf_20180425_programid2 -> night=20180425, program=MSIP
      - source_labels: [ topic ]
        regex: "ztf_(\\d+)_.*"
        target_label: "night"
        replacement: "$1"
      - source_labels: [ topic ]
        regex: "ztf_\\d+_programid0"
        target_label: "program"
        replacement: "Commissioning"
      - source_labels: [ topic ]
        regex: "ztf_\\d+_programid1"
        target_label: "program"
        replacement: "MSIP"
